services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: levanngoc_dev
    volumes:
      - levanngoc_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - levanngoc-networks

volumes:
  levanngoc_data:
  
networks:
  levanngoc-networks:
    driver: bridge
